# 各模块的开关
ModuleSwitch:
  #B站动态订阅
  Bili_Subscription: false
  #公主连结国服动态订阅
  PCR_Subscription: false
  #切噜语翻译
  Cheru: false
  #奇怪的娱乐功能 (随机禁言啥的)
  HaveFun: false
  #随机色图
  Hso: false
  #公会战管理
  PCR_GuildManager: true
  #公会排名查询
  PCR_GuildRank: false
  #调试模块
  Debug: false
  #拍卖机器人模块
  Auction: true

# 随机色图设置
HsoConfig:
  #色图源 Local/Lolicon/Yukari
  Source: Local
  #Pximy代理服务器地址，如果没有设置为null即可
  PximyProxy: null
  #是否使用本地缓存
  UseCache: false
  #是否使用XML格式发送图片（装逼大图）
  #有被风控风险谨慎启用
  #此功能只能在Go上使用
  CardImage: false
  #色图缓存文件夹的大小限制(MB)
  SizeLimit: 1024
  #Lolicon APIKEY
  LoliconToken: null
  #Yukari APIKEY
  YukariToken: null

# 动态订阅设置
SubscriptionConfig:
  #刷新时间(最小值10)
  FlashTime: 60
  #群组订阅设置
  GroupsConfig:
    - GroupId: [] #群号，可以一次设置多个群
      PCR_Subscription: false #PCR国服动态订阅
      SubscriptionId: [] #B站用户ID